export enum Faction {
  Reich,
  Union,
}

export const StringToFaction = (fac: string): Faction => {
  if (fac === "Reich") return Faction.Reich;
  return Faction.Union;
}

export interface CharacterData {
  name: string;
  image: string;
  faction: Faction;
  token_image: string;
  card_back_image: string;
  deck: string[];
}

export interface Characters {
  [key: string] : CharacterData;
}

const app_base_folder = "app/modules/tannhauser/";
const reich_cards_folder = app_base_folder + "img/Solo_Reich_cards/";
const union_cards_folder = app_base_folder + "img/Solo_Union_cards/";

export const AllCharacters: Characters = {
  Eva: {
    name: "Eva Krämer",
    faction: Faction.Reich,
    image: app_base_folder + "img/eva.png",
    token_image: app_base_folder + "img/eva-token.png",
    card_back_image: reich_cards_folder + "Rbacks.jpg",
    deck: [
      reich_cards_folder + "Eva/Eva1.jpg",
      reich_cards_folder + "Eva/Eva2.jpg",
      reich_cards_folder + "Eva/Eva3.jpg",
      reich_cards_folder + "Eva/Eva4.jpg",
      reich_cards_folder + "Eva/Eva5.jpg",
      reich_cards_folder + "Eva/Eva6.jpg",
      reich_cards_folder + "Eva/Eva7.jpg",
      reich_cards_folder + "Eva/Eva8.jpg",
      reich_cards_folder + "Eva/Eva9.jpg",
      reich_cards_folder + "Eva/Eva10.jpg",
      reich_cards_folder + "Eva/Eva12.jpg",
      reich_cards_folder + "Eva/Eva34.jpg",
    ],
  },
  Frankenstahl: {
    name: "Frankenstahl",
    faction: Faction.Reich,
    image: app_base_folder + "img/frankenstahl.png",
    token_image: app_base_folder + "img/frankenstahl-token.png",
    card_back_image: reich_cards_folder + "Rbacks.jpg",
    deck: [
      reich_cards_folder + "Frankenstahl/Frank1.jpg",
      reich_cards_folder + "Frankenstahl/Frank2.jpg",
      reich_cards_folder + "Frankenstahl/Frank3.jpg",
      reich_cards_folder + "Frankenstahl/Frank4.jpg",
      reich_cards_folder + "Frankenstahl/Frank5.jpg",
      reich_cards_folder + "Frankenstahl/Frank6.jpg",
      reich_cards_folder + "Frankenstahl/Frank7.jpg",
      reich_cards_folder + "Frankenstahl/Frank8.jpg",
      reich_cards_folder + "Frankenstahl/Frank9.jpg",
      reich_cards_folder + "Frankenstahl/Frank10.jpg",
    ],
  },
  Ozo: {
    name: "Karl 'Ozo' Zermann",
    faction: Faction.Reich,
    image: app_base_folder + "img/ozo.png",
    token_image: app_base_folder + "img/ozo-token.png",
    card_back_image: reich_cards_folder + "Rbacks.jpg",
    deck: [
      reich_cards_folder + "Ozo/Ozo1.jpg",
      reich_cards_folder + "Ozo/Ozo2.jpg",
      reich_cards_folder + "Ozo/Ozo3.jpg",
      reich_cards_folder + "Ozo/Ozo4.jpg",
      reich_cards_folder + "Ozo/Ozo5.jpg",
      reich_cards_folder + "Ozo/Ozo6.jpg",
      reich_cards_folder + "Ozo/Ozo7.jpg",
      reich_cards_folder + "Ozo/Ozo8.jpg",
      reich_cards_folder + "Ozo/Ozo9.jpg",
      reich_cards_folder + "Ozo/Ozo10.jpg",
    ],
  },
  Schocktruppen: {
    name: "Schocktruppen",
    faction: Faction.Reich,
    image: app_base_folder + "img/schocktruppen.png",
    token_image: app_base_folder + "img/schocktruppen-token.png",
    card_back_image: reich_cards_folder + "Rbacks.jpg",
    deck: [
      reich_cards_folder + "Schocktruppen/Schock1.JPG",
      reich_cards_folder + "Schocktruppen/Schock2.JPG",
      reich_cards_folder + "Schocktruppen/Schock3.JPG",
      reich_cards_folder + "Schocktruppen/Schock4.JPG",
      reich_cards_folder + "Schocktruppen/Schock5.JPG",
      reich_cards_folder + "Schocktruppen/Schock6.JPG",
      reich_cards_folder + "Schocktruppen/Schock7.JPG",
      reich_cards_folder + "Schocktruppen/Schock8.JPG",
      reich_cards_folder + "Schocktruppen/Schock9.JPG",
      reich_cards_folder + "Schocktruppen/Schock10.JPG",
    ],
  },
  Stosstruppen: {
    name: "Stosstruppen",
    faction: Faction.Reich,
    image: app_base_folder + "img/stosstruppen.png",
    token_image: app_base_folder + "img/stosstruppen-token.png",
    card_back_image: reich_cards_folder + "Rbacks.jpg",
    deck: [
      reich_cards_folder + "Stosstruppen/Stoss1.jpg",
      reich_cards_folder + "Stosstruppen/Stoss2.jpg",
      reich_cards_folder + "Stosstruppen/Stoss3.jpg",
      reich_cards_folder + "Stosstruppen/Stoss5.jpg",
      reich_cards_folder + "Stosstruppen/Stoss6.jpg",
      reich_cards_folder + "Stosstruppen/Stoss7.jpg",
      reich_cards_folder + "Stosstruppen/Stoss8.jpg",
      reich_cards_folder + "Stosstruppen/Stoss9.jpg",
      reich_cards_folder + "Stosstruppen/Stoss10.jpg",
      reich_cards_folder + "Stosstruppen/Stoss11.jpg",
    ],
  },
  Heizinger: {
    name: "Hermann Von Heïzinger",
    faction: Faction.Reich,
    image: app_base_folder + "img/heizinger.png",
    token_image: app_base_folder + "img/heizinger-token.png",
    card_back_image: reich_cards_folder + "Rbacks.jpg",
    deck: [
      reich_cards_folder + "von Heizinger/Heizinger1.jpg",
      reich_cards_folder + "von Heizinger/Heizinger2.jpg",
      reich_cards_folder + "von Heizinger/Heizinger3.jpg",
      reich_cards_folder + "von Heizinger/Heizinger4.jpg",
      reich_cards_folder + "von Heizinger/Heizinger5.jpg",
      reich_cards_folder + "von Heizinger/Heizinger6.jpg",
      reich_cards_folder + "von Heizinger/Heizinger7.jpg",
      reich_cards_folder + "von Heizinger/Heizinger8.jpg",
      reich_cards_folder + "von Heizinger/Heizinger9.jpg",
      reich_cards_folder + "von Heizinger/Heizinger10.jpg",
      reich_cards_folder + "von Heizinger/Heizinger11.jpg",
      reich_cards_folder + "von Heizinger/Heizinger12.jpg",
      reich_cards_folder + "von Heizinger/Heizinger13.jpg",
      reich_cards_folder + "von Heizinger/Heizinger14.jpg",
    ],
  },
  Yula: {
    name: "Yula Korlïtz",
    faction: Faction.Reich,
    image: app_base_folder + "img/yula.png",
    token_image: app_base_folder + "img/yula-token.png",
    card_back_image: reich_cards_folder + "Rbacks.jpg",
    deck: [
      reich_cards_folder + "Yula/Yula1a.jpg",
      reich_cards_folder + "Yula/Yula2.jpg",
      reich_cards_folder + "Yula/Yula3.jpg",
      reich_cards_folder + "Yula/Yula4.jpg",
      reich_cards_folder + "Yula/Yula5.jpg",
      reich_cards_folder + "Yula/Yula6.jpg",
      reich_cards_folder + "Yula/Yula7.jpg",
      reich_cards_folder + "Yula/Yula8.jpg",
      reich_cards_folder + "Yula/Yula9.jpg",
      reich_cards_folder + "Yula/Yula10.jpg",
      reich_cards_folder + "Yula/Yula111.jpg",
    ],
  },
  Alpha: {
    name: "Commando Alpha",
    faction: Faction.Union,
    image: app_base_folder + "img/alpha.png",
    token_image: app_base_folder + "img/alpha-token.png",
    card_back_image: union_cards_folder + "UnionBack.jpg",
    deck: [
      union_cards_folder + "Alpha/Alpha1.jpg",
      union_cards_folder + "Alpha/Alpha2.jpg",
      union_cards_folder + "Alpha/Alpha3.jpg",
      union_cards_folder + "Alpha/Alpha4.jpg",
      union_cards_folder + "Alpha/Alpha5.jpg",
      union_cards_folder + "Alpha/Alpha6.jpg",
      union_cards_folder + "Alpha/Alpha7.jpg",
      union_cards_folder + "Alpha/Alpha8.jpg",
      union_cards_folder + "Alpha/Alpha9.jpg",
      union_cards_folder + "Alpha/Alpha10.jpg",
    ],
  },
  Barry: {
    name: "Barry Daniel Brown",
    faction: Faction.Union,
    image: app_base_folder + "img/brown.png",
    token_image: app_base_folder + "img/brown-token.png",
    card_back_image: union_cards_folder + "UnionBack.jpg",
    deck: [
      union_cards_folder + "BarryBrown/Barry1.jpg",
      union_cards_folder + "BarryBrown/Barry2.jpg",
      union_cards_folder + "BarryBrown/Barry3.jpg",
      union_cards_folder + "BarryBrown/Barry4.jpg",
      union_cards_folder + "BarryBrown/Barry5.jpg",
      union_cards_folder + "BarryBrown/Barry6.jpg",
      union_cards_folder + "BarryBrown/Barry7.jpg",
      union_cards_folder + "BarryBrown/Barry8.jpg",
      union_cards_folder + "BarryBrown/Barry9.jpg",
      union_cards_folder + "BarryBrown/Barry10.jpg",
    ],
  },
  Delta: {
    name: "Commando Delta",
    faction: Faction.Union,
    image: app_base_folder + "img/delta.png",
    token_image: app_base_folder + "img/delta-token.png",
    card_back_image: union_cards_folder + "UnionBack.jpg",
    deck: [
      union_cards_folder + "Delta/delta1.jpg",
      union_cards_folder + "Delta/delta2.jpg",
      union_cards_folder + "Delta/delta3.jpg",
      union_cards_folder + "Delta/delta4.jpg",
      union_cards_folder + "Delta/delta5.jpg",
      union_cards_folder + "Delta/delta6.jpg",
      union_cards_folder + "Delta/delta7.jpg",
      union_cards_folder + "Delta/delta8.jpg",
      union_cards_folder + "Delta/delta9.jpg",
      union_cards_folder + "Delta/delta10.jpg",
    ],
  },
  Edison: {
    name: "James Edison",
    faction: Faction.Union,
    image: app_base_folder + "img/edison.png",
    token_image: app_base_folder + "img/edison-token.png",
    card_back_image: union_cards_folder + "UnionBack.jpg",
    deck: [
      union_cards_folder + "Edison/Edison1.jpg",
      union_cards_folder + "Edison/Edison2.jpg",
      union_cards_folder + "Edison/Edison3.jpg",
      union_cards_folder + "Edison/Edison4.jpg",
      union_cards_folder + "Edison/Edison5.jpg",
      union_cards_folder + "Edison/Edison6.jpg",
      union_cards_folder + "Edison/Edison7.jpg",
      union_cards_folder + "Edison/Edison8.jpg",
      union_cards_folder + "Edison/Edison9.jpg",
      union_cards_folder + "Edison/Edison10.jpg",
    ],
  },
  Hoax: {
    name: "Caitlin 'Hoax' Lamsbury",
    faction: Faction.Union,
    image: app_base_folder + "img/hoax.png",
    token_image: app_base_folder + "img/hoax-token.png",
    card_back_image: union_cards_folder + "UnionBack.jpg",
    deck: [
      union_cards_folder + "Hoax/hoax1.jpg",
      union_cards_folder + "Hoax/hoax2.jpg",
      union_cards_folder + "Hoax/hoax3.jpg",
      union_cards_folder + "Hoax/hoax4.jpg",
      union_cards_folder + "Hoax/hoax5.jpg",
      union_cards_folder + "Hoax/hoax6.jpg",
      union_cards_folder + "Hoax/hoax7.jpg",
      union_cards_folder + "Hoax/hoax8.jpg",
      union_cards_folder + "Hoax/hoax9.jpg",
      union_cards_folder + "Hoax/hoax10.jpg",
      union_cards_folder + "Hoax/hoax11.jpg",
      union_cards_folder + "Hoax/hoax12.jpg",
    ],
  },
  MacNeal: {
    name: "John MacNeal",
    faction: Faction.Union,
    image: app_base_folder + "img/macneal.png",
    token_image: app_base_folder + "img/macneal-token.png",
    card_back_image: union_cards_folder + "UnionBack.jpg",
    deck: [
      union_cards_folder + "MacNeal/MacNeal1.jpg",
      union_cards_folder + "MacNeal/MacNeal2.jpg",
      union_cards_folder + "MacNeal/MacNeal3.jpg",
      union_cards_folder + "MacNeal/MacNeal4.jpg",
      union_cards_folder + "MacNeal/MacNeal5.jpg",
      union_cards_folder + "MacNeal/MacNeal6.jpg",
      union_cards_folder + "MacNeal/MacNeal7.jpg",
      union_cards_folder + "MacNeal/MacNeal8.jpg",
      union_cards_folder + "MacNeal/MacNeal9.jpg",
      union_cards_folder + "MacNeal/MacNeal10.jpg",
      union_cards_folder + "MacNeal/MacNeal11.jpg",
      union_cards_folder + "MacNeal/MacNeal12.jpg",
    ],
  },
  Ramirez: {
    name: "Sergio Ramirez Delastillas",
    faction: Faction.Union,
    image: app_base_folder + "img/ramirez.png",
    token_image: app_base_folder + "img/ramirez-token.png",
    card_back_image: union_cards_folder + "UnionBack.jpg",
    deck: [
      union_cards_folder + "Ramirez/ramirez1.jpg",
      union_cards_folder + "Ramirez/ramirez2.jpg",
      union_cards_folder + "Ramirez/ramirez3.jpg",
      union_cards_folder + "Ramirez/ramirez4.jpg",
      union_cards_folder + "Ramirez/ramirez5.jpg",
      union_cards_folder + "Ramirez/ramirez6.jpg",
      union_cards_folder + "Ramirez/ramirez7.jpg",
      union_cards_folder + "Ramirez/ramirez8.jpg",
      union_cards_folder + "Ramirez/ramirez9.jpg",
      union_cards_folder + "Ramirez/ramirez10.jpg",
      union_cards_folder + "Ramirez/ramirez11.jpg",
    ],
  },
  Hound: {
    name: "Hound Dog",
    faction: Faction.Union,
    image: union_cards_folder + "Ramirez/HoundDog/HDtempRULES.jpg",
    token_image: app_base_folder + "img/hound_dog-token.png",
    card_back_image: union_cards_folder + "Ramirez/HoundDog/HDBack.jpg",
    deck: [
      union_cards_folder + "Ramirez/HoundDog/HDtemp.jpg",
      union_cards_folder + "Ramirez/HoundDog/HDtemp2.jpg",
      union_cards_folder + "Ramirez/HoundDog/HDtemp3.jpg",
      union_cards_folder + "Ramirez/HoundDog/HDtemp4.jpg",
      union_cards_folder + "Ramirez/HoundDog/HDtemp5.jpg",
    ],
  },
  Tala: {
    name: "Tala Aponi",
    faction: Faction.Union,
    image: app_base_folder + "img/tala.png",
    token_image: app_base_folder + "img/tala-token.png",
    card_back_image: union_cards_folder + "UnionBack.jpg",
    deck: [
      union_cards_folder + "Tala/Tala1.jpg",
      union_cards_folder + "Tala/tala2.jpg",
      union_cards_folder + "Tala/tala3.jpg",
      union_cards_folder + "Tala/tala4.jpg",
      union_cards_folder + "Tala/tala5.jpg",
      union_cards_folder + "Tala/tala6.jpg",
      union_cards_folder + "Tala/tala7.jpg",
      union_cards_folder + "Tala/tala8.jpg",
      union_cards_folder + "Tala/tala9.jpg",
      union_cards_folder + "Tala/tala10.jpg",
    ],
  },
};
